unique_ids:
  assets:
    standard-page.html: MNYKQW2JKTNAI6MXYV3DDCA5NESGZTWP
    theme.css: JFOIZMJMLB2WWTWONTM6T3Y2WQT3OVF7
  forms:
    Form1: 47KTJCT3LSWDYDKY25NVCJATJ6MURZM2
  modules: {}
  scripts: {}
  server_modules: {}
